baseURL = 'https://docs.iita.net/'
languageCode = 'zh-cn'
title = '文档'
theme = "book"

[params]
  BookTheme = "auto"
  BookToC = true
  BookSection = "docs"

[menu]
[[menu.home]]
  name = "首页"
  pageRef = "/"
  weight = 1

[[menu.home]]
  name = "知识库"
  pageRef = "/docs"
  weight = 2

[[menu.home]]
  name = "工具"
  pageRef = "/docs/jiaocheng"
  weight = 3

[[menu.home]]
  name = "关于"
  pageRef = "/about"
  weight = 4

[languages]
  [languages.zh]
    languageName = "中文"
    contentDir = "content"
