baseURL = 'https://docs.iita.net/'
languageCode = 'zh-cn'
title = '文档'
theme = "book"

[params]
  BookTheme = "auto"
  BookToC = true
  BookSection = "docs"

[languages]
  [languages.zh]
    languageName = "中文"
    contentDir = "content"
